#!/usr/bin/env node
/* Copies framework-neutral core files into the Svelte package.
 *
 * The React package keeps `dependencies: {}` — the website publishes that
 * figure — so core cannot become an installed runtime dependency. It is shared
 * at source level instead: each consumer carries its own copy of the pure files.
 * The React package bundles them with tsup; the Svelte package ships source via
 * @sveltejs/package, which cannot follow an import out of its own directory, so
 * the files are copied in.
 *
 * Copies are verbatim plus a header, from an explicit allowlist, and a file
 * that imports a framework is refused rather than copied — one stray React
 * import here would put React in every Svelte consumer's bundle.
 *
 *   node scripts/vendor-core.js           write the copies
 *   node scripts/vendor-core.js --check   exit 1 if any copy is stale or missing
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs'
import { resolve, dirname, relative, join } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const DEST = resolve(ROOT, 'packages/svelte/src/vendor')

// Add a file here only after confirming it imports nothing but other entries.
const ALLOWLIST = [
  'src/core/a11y/compute-anchor-position.ts',
  'src/core/icons/paths.ts',
]

const FRAMEWORK_IMPORT = /from\s+['"](react|react-dom|react\/[^'"]*|svelte|svelte\/[^'"]*)['"]/
const RELATIVE_IMPORT = /from\s+['"](\.{1,2}\/[^'"]+)['"]/g

const check = process.argv.includes('--check')
let failed = false
const expected = new Map()

for (const rel of ALLOWLIST) {
  const src = resolve(ROOT, rel)
  if (!existsSync(src)) {
    console.error(`[vendor-core] FAIL: ${rel} does not exist`)
    failed = true
    continue
  }
  const text = readFileSync(src, 'utf8')
  const fw = text.match(FRAMEWORK_IMPORT)
  if (fw) {
    console.error(`[vendor-core] FAIL: ${rel} imports ${fw[1]} — only framework-neutral files may be vendored`)
    failed = true
    continue
  }
  for (const m of text.matchAll(RELATIVE_IMPORT)) {
    const target = relative(ROOT, resolve(dirname(src), m[1])).replace(/\.(ts|js)$/, '')
    if (!ALLOWLIST.some(a => a.replace(/\.ts$/, '') === target)) {
      console.error(`[vendor-core] FAIL: ${rel} imports ${m[1]}, which is not on the allowlist — the copy would not resolve`)
      failed = true
    }
  }
  const header = `/* GENERATED by scripts/vendor-core.js from ${rel} — do not edit.\n * Edit the source and run \`npm run vendor:core\`. */\n\n`
  expected.set(resolve(DEST, relative('src', rel)), header + text)
}

if (failed) process.exit(1)

// Positive control: the framework check must be able to fire.
if (!FRAMEWORK_IMPORT.test(`import { useState } from 'react'`)) {
  console.error('[vendor-core] FAIL: framework pattern does not match a known-bad sample')
  process.exit(1)
}

function walk(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir, { withFileTypes: true }).flatMap(e =>
    e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)])
}

if (check) {
  for (const [path, body] of expected) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== body) {
      console.error(`[vendor-core] STALE: ${relative(ROOT, path)} — run \`npm run vendor:core\``)
      failed = true
    }
  }
  for (const path of walk(DEST)) {
    if (!expected.has(path)) {
      console.error(`[vendor-core] STALE: ${relative(ROOT, path)} is not on the allowlist — remove it`)
      failed = true
    }
  }
  if (failed) process.exit(1)
  console.log(`[vendor-core] fresh: ${expected.size} file(s)`)
} else {
  rmSync(DEST, { recursive: true, force: true })
  for (const [path, body] of expected) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, body)
  }
  console.log(`[vendor-core] wrote ${expected.size} file(s) to ${relative(ROOT, DEST)}`)
}
