import { describe, it, expect } from 'vitest'
import { render } from '@testing-library/svelte'
import { flushSync } from 'svelte'
import { createRawSnippet, type Component } from 'svelte'
import * as pkg from '../../src/index.js'
import fixture from '../fixtures/contract.json'
import { CASES } from './cases.js'
import { canonical, fromHtml } from './canonical.js'
import { DIVERGENCES, NO_SSR_CONTRACT } from './divergences.js'

/* Every Svelte component must render the same DOM tree as its React
 * counterpart, for every case in cases.ts. React's side is server HTML
 * generated by scripts/generate-contract-fixtures.tsx; `test:contract-fresh`
 * fails if it goes stale. Components are looked up from the package's own
 * exports, so what is tested is what ships. */

type Fixture = { version: number; components: Record<string, Record<string, { props: unknown; html: string }>> }
const f = fixture as Fixture

function hydrate(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(hydrate)
  if (value && typeof value === 'object') {
    const v = value as Record<string, unknown>
    if ('$el' in v) {
      const text = String(v.$el).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c]!)
      return createRawSnippet(() => ({ render: () => `<b>${text}</b>` }))
    }
    if ('$fn' in v) return () => {}
    return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, hydrate(x)]))
  }
  return value
}

const exported = Object.entries(pkg)
  .filter(([name, v]) => /^[A-Z]/.test(name) && typeof v === 'function')
  .map(([name]) => name)
  .sort()

describe('React DOM contract', () => {
  it('uses the v2 full-tree fixture', () => {
    expect(f.version).toBe(2)
  })

  // The fixture and the case file must agree, or the fixture is stale.
  it('fixture covers exactly the cases in cases.ts', () => {
    const fromCases = Object.fromEntries(Object.entries(CASES).map(([n, c]) => [n, Object.keys(c).sort()]))
    const fromFixture = Object.fromEntries(Object.entries(f.components).map(([n, c]) => [n, Object.keys(c).sort()]))
    expect(fromFixture).toEqual(fromCases)
  })

  // Denominator: every shipped component is contract-tested or excused by name.
  it('every exported component is in the contract or explicitly excused', () => {
    const uncovered = exported.filter(n => !(n in f.components) && !(n in NO_SSR_CONTRACT))
    expect(uncovered).toEqual([])
    const stale = Object.keys(NO_SSR_CONTRACT).filter(n => n in f.components || !exported.includes(n))
    expect(stale).toEqual([])
  })

  /* Generic: the getter rule. A Svelte <script> body runs once, so a rune fed a
   * prop VALUE snapshots it and later changes never reach the DOM — the bug
   * Badge shipped with in PR #1. Checked here for every component whose
   * React markup carries data-motion, rather than copied into each test file. */
  for (const [name, cases] of Object.entries(f.components)) {
    const withMotion = Object.entries(cases).find(([, c]) => c.html.includes('data-motion'))
    if (!withMotion) continue
    it(`${name}: data-motion follows a motion prop change after mount`, async () => {
      const Comp = (pkg as Record<string, unknown>)[name] as Component<any>
      const base = hydrate(withMotion[1].props) as Record<string, unknown>
      const { container, rerender } = render(Comp, { props: { ...base, motion: 1 } })
      const read = () => Array.from(container.querySelectorAll('[data-motion]')).map(e => e.getAttribute('data-motion'))
      expect(read().length).toBeGreaterThan(0)
      expect(new Set(read())).toEqual(new Set(['1']))
      await rerender({ ...base, motion: 0 })
      flushSync()
      expect(new Set(read())).toEqual(new Set(['0']))
    })
  }

  for (const [name, cases] of Object.entries(f.components)) {
    describe(name, () => {
      it('is exported by the package', () => {
        expect(exported).toContain(name)
      })

      for (const [caseName, { props, html }] of Object.entries(cases)) {
        it(caseName, () => {
          const Comp = (pkg as Record<string, unknown>)[name] as Component<any>
          const { container } = render(Comp, { props: hydrate(props) as Record<string, unknown> })
          // CSP: where React's markup has no inline style at all, Svelte must
          // not either. Checked before divergences, which may add style to
          // mirror React's shape.
          if (!/\sstyle="/.test(html)) expect(container.querySelector('[style]')).toBeNull()
          for (const d of DIVERGENCES[name] ?? []) d.apply(container)
          expect(canonical(container)).toBe(canonical(fromHtml(html)))
        })
      }
    })
  }
})
