import { describe, it, expect, vi, beforeAll, afterAll } from 'vitest'
import { render } from '@testing-library/svelte'
import { flushSync } from 'svelte'
import { createRawSnippet, type Component } from 'svelte'
import * as pkg from '../../src/index.js'
import fixture from '../fixtures/contract.json'
import { CASES, CONTRACT_NOW } from './cases.js'
import { canonical, fromHtml } from './canonical.js'
import { DIVERGENCES, EFFECT_ATTRS, EFFECT_STYLES, EFFECT_VALUES, NO_SSR_CONTRACT, PROP_RENAMES, UNIVERSAL_RENAMES } from './divergences.js'

/* Every Svelte component must render the same DOM tree as its React
 * counterpart, for every case in cases.ts. React's side is server HTML
 * generated by scripts/generate-contract-fixtures.tsx; `test:contract-fresh`
 * fails if it goes stale. Components are looked up from the package's own
 * exports, so what is tested is what ships. */

type Fixture = { version: number; components: Record<string, Record<string, { props: unknown; html: string }>> }
const f = fixture as Fixture

function renamed(name: string, props: unknown): Record<string, unknown> {
  const out = { ...(props as Record<string, unknown>) }
  for (const { from, to } of [...UNIVERSAL_RENAMES, ...(PROP_RENAMES[name] ?? [])]) {
    if (from in out) { out[to] = out[from]; delete out[from] }
  }
  return out
}

function hydrate(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(hydrate)
  if (value && typeof value === 'object') {
    const v = value as Record<string, unknown>
    if ('$el' in v) {
      const text = String(v.$el).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c]!)
      return createRawSnippet(() => ({ render: () => `<b>${text}</b>` }))
    }
    if ('$fn' in v) return () => {}
    if ('$date' in v) return new Date(String(v.$date))
    return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, hydrate(x)]))
  }
  return value
}

const exported = Object.entries(pkg)
  .filter(([name, v]) => /^[A-Z]/.test(name) && typeof v === 'function')
  .map(([name]) => name)
  .sort()

describe('React DOM contract', () => {
  // Same clock as the generator, so relative times render identically. Date
  // and setTimeout are faked; microtasks are not, so Svelte's scheduling is
  // untouched. setTimeout is faked so an entrance animation (useEntrance) can be
  // run to its settled state — React's server render never runs effects, so the
  // settled DOM is the fair comparison.
  beforeAll(() => { vi.useFakeTimers({ toFake: ['Date', 'setTimeout', 'clearTimeout'] }); vi.setSystemTime(CONTRACT_NOW) })
  afterAll(() => { vi.useRealTimers() })

  it('uses the v2 full-tree fixture', () => {
    expect(f.version).toBe(2)
  })

  // The fixture and the case file must agree, or the fixture is stale.
  it('fixture covers exactly the cases in cases.ts', () => {
    const fromCases = Object.fromEntries(Object.entries(CASES).map(([n, c]) => [n, Object.keys(c).sort()]))
    const fromFixture = Object.fromEntries(Object.entries(f.components).map(([n, c]) => [n, Object.keys(c).sort()]))
    expect(fromFixture).toEqual(fromCases)
  })

  // Denominator: every shipped component is contract-tested or excused by name.
  it('every exported component is in the contract or explicitly excused', () => {
    const uncovered = exported.filter(n => !(n in f.components) && !(n in NO_SSR_CONTRACT))
    expect(uncovered).toEqual([])
    const stale = Object.keys(NO_SSR_CONTRACT).filter(n => n in f.components || !exported.includes(n))
    expect(stale).toEqual([])
  })

  /* Generic: the getter rule. A Svelte <script> body runs once, so a rune fed a
   * prop VALUE snapshots it and later changes never reach the DOM — the bug
   * Badge shipped with in PR #1. Checked here for every component whose
   * React markup carries data-motion, rather than copied into each test file.
   *
   * Which elements follow the prop is read from React, not assumed: in a
   * composite such as ConfirmDialog only the Dialog receives `motion`, and its
   * Buttons keep the context default. The React render of the component's
   * `motion: 0` case says which elements carry the prop's value; those must
   * track every change, and the rest must keep React's value. */
  const motions = (html: string) => Array.from(html.matchAll(/data-motion="([^"]*)"/g), m => m[1])
  for (const [name, cases] of Object.entries(f.components)) {
    const withMotion = Object.entries(cases).find(([, c]) => c.html.includes('data-motion'))
    if (!withMotion) continue
    const zeroCase = Object.values(cases).find(c => (c.props as { motion?: unknown }).motion === 0 && c.html.includes('data-motion'))
    it(`${name}: data-motion follows a motion prop change after mount`, async () => {
      const Comp = (pkg as Record<string, unknown>)[name] as Component<any>
      const base = hydrate(renamed(name, (zeroCase ?? withMotion[1]).props)) as Record<string, unknown>
      const react = zeroCase ? motions(zeroCase.html) : null
      const expected = (level: number) =>
        react ? react.map(v => (v === '0' ? String(level) : v)) : null
      const { container, rerender } = render(Comp, { props: { ...base, motion: 1 } })
      const read = () => Array.from(container.querySelectorAll('[data-motion]')).map(e => e.getAttribute('data-motion'))
      expect(read().length).toBeGreaterThan(0)
      if (react) {
        expect(react).toContain('0')
        expect(read()).toEqual(expected(1))
      } else expect(new Set(read())).toEqual(new Set(['1']))
      await rerender({ ...base, motion: 0 })
      flushSync()
      if (react) expect(read()).toEqual(expected(0))
      else expect(new Set(read())).toEqual(new Set(['0']))
    })
  }

  for (const [name, cases] of Object.entries(f.components)) {
    describe(name, () => {
      it('is exported by the package', () => {
        expect(exported).toContain(name)
      })

      for (const [caseName, { props, html }] of Object.entries(cases)) {
        it(caseName, () => {
          const Comp = (pkg as Record<string, unknown>)[name] as Component<any>
          // Reset per render: runAllTimers advances the faked Date by every timer it
          // runs, so without this the clock drifts across cases and relative
          // times ("30 seconds ago") stop matching.
          vi.setSystemTime(CONTRACT_NOW)
          const { container } = render(Comp, { props: hydrate(renamed(name, props)) as Record<string, unknown> })
          vi.runAllTimers()
          flushSync()
          // CSP: where React's markup has no inline style at all, Svelte must
          // not either. An empty style attribute — left behind when an entrance
          // animation clears the properties it set — carries no CSS. Checked
          // before divergences, which may add style to mirror React's shape.
          for (const { selector, properties } of EFFECT_STYLES[name] ?? []) {
            for (const el of Array.from(container.querySelectorAll<HTMLElement>(selector))) {
              for (const p of properties) el.style.removeProperty(p)
              if (el.getAttribute('style') === '') el.removeAttribute('style')
            }
          }
          for (const { selector, attributes } of EFFECT_ATTRS[name] ?? []) {
            for (const el of Array.from(container.querySelectorAll(selector))) for (const a of attributes) el.removeAttribute(a)
          }
          for (const { selector } of EFFECT_VALUES[name] ?? []) {
            for (const el of Array.from(container.querySelectorAll<HTMLInputElement>(selector))) {
              el.value = ''
              el.removeAttribute('value')
            }
          }
          if (!/\sstyle="/.test(html)) expect(container.querySelector('[style]:not([style=""])')).toBeNull()
          for (const d of DIVERGENCES[name] ?? []) d.apply(container)
          expect(canonical(container)).toBe(canonical(fromHtml(html)))
        })
      }
    })
  }
})
